### ISSUE TITLE
MainNet request hanging

### ISSUE THREAD

**Issue by dblodorn** [ourzora/nft-hooks#56]
After updating to 0.5.1 I have been experiencing a timeout in requests to mainnet, if network id is set to rinkeby I am not experiencing this.

A flag to allow for logging on the server would help with debugging. Especially since the timeout blocks the site from loading in the browser or building in vercel.

Getting some insight into if there is an issue upstream or with however our app is configured or with the nft-components would be valuable.

**Comment by iainnash** [comment]
Is this issue still occurring?

**Comment by iainnash** [comment]
Unable to re-create this so closing this ticket for now.
